import { MODEL_AD, MODEL_AD_TR, LAYA_GITHUB, LAYA_HF, MOGANBERT_HF, MOGANBERT_MAKALE, MOGAN_SITE, LAVOIR_KOD, LAVOIR_TR_HF } from './sabitler';

// LAVOIR-TR sayfasinin metinleri. i18n.jsx bunlari secili dilde METIN'in
// ustune bolum bolum bindirir: burada olmayan anahtarlar (animasyon
// metinleri, VOI bolumu, sorun bolumu...) Ingilizce modelin sayfasindan gelir.
// Sayilar laya_voi/ILERLEME.md (egitim 2006681, degerlendirme 2007893,
// Laya kiyasi 2008372, sifir atis 2008175).
export const METIN_TR = {
  tr: {
    modelAd: MODEL_AD_TR,
    navSira: ['giris', 'moganbert', 'laya', 'voi', 'veri', 'sonuc', 'kaynak'],
    hero: {
      alt: 'Türkçe karar modeli · MoganBERT-TR üzerine',
      logo: { src: 'lavoir-tr-logo.png', w: 1248, h: 340, gen: 'max-w-[290px] sm:max-w-[340px] md:max-w-[390px]' },
      baglanti: { hf: LAVOIR_TR_HF, paper: '', kod: LAVOIR_KOD },
      ozet: [MODEL_AD_TR + ', ' + MODEL_AD + '’un Türkçe sürümü ve ',
             'kendi sıfırdan eğittiğimiz Türkçe encoder MoganBERT-TR üzerine kurulu',
             '. Aynı karar mimarisi ve VOI başlığı Türkçe iş akışlarıyla eğitildi: e-Devlet, SGK, belediye, KVKK, bankacılık gibi alanlardaki Türkçe müşteri mesajlarında eksik bilgiyi soruyor, cevabı alınca yeniden karar veriyor.'],
      metaSol: 'SÜRÜM 1 · TÜRKÇE',
      gercek: [
        { k: 'ENCODER', v: 'MoganBERT-TR (MoganAI)' },
        { k: 'MODEL BOYUTU', v: '164M parametre' },
        { k: 'İŞ AKIŞI', v: '16 Türkçe şema' },
        { k: 'TEMEL', v: 'Laya karar mimarisi' },
      ],
    },
    moganbert: {
      baslik: 'MOGANBERT-TR ÜZERİNE KURULU',
      p1: [MODEL_AD_TR + '’nin encoder’ı ', 'MoganBERT-TR',
           ': Türkçe için sıfırdan, CLM → MLM müfredatıyla eğittiğimiz ModernBERT mimarili encoder. Karar ve VOI başlıkları bu encoder’ın üstünde sıfırdan eğitildi; çok dilli bir modelden ya da İngilizce ' + MODEL_AD + '’dan ağırlık aktarılmadı.'],
      p2: ['Türkçeye özel bir encoder kullanmanın iki etkisi var. ',
           'Aynı Türkçe mesaj MoganBERT-TR’nin tokenizer’ıyla 122, ModernBERT’inkiyle 222 token tutuyor',
           ': sekans kısalıyor ve iş akışının seçenek ve slot listesine daha çok yer kalıyor. Model de İngilizce sürümün yarısından küçük, ama soru seçmede aynı düzeyde.'],
      p3: ['MoganBERT-TR’nin [CLS] token’ı ön eğitimde kullanılmadı. Bu ' + MODEL_AD_TR + ' için sorun değil: karar ve bilgi değeri [CLS]’den değil, seçenek ve slot başındaki [MASK] işaretçilerinden okunuyor. Özel token’ların düzeni Laya’nın sekans biçimiyle uyumlu, bağlam uzunluğu 1.024 token.'],
      kiyasBaslik: MODEL_AD + ' VE ' + MODEL_AD_TR,
      kiyasAlt: 'aynı mimari · farklı encoder',
      thOzellik: 'ÖZELLİK',
      kiyas: [
        ['Encoder', 'ModernBERT-large', 'MoganBERT-TR (MoganAI)'],
        ['Toplam parametre', '421M', '164M'],
        ['Aynı Türkçe mesaj', '222 token', '122 token'],
        ['Eğitim verisi', '~104k örnek', '~136k örnek (20k’sı İngilizce)'],
        ['İş akışı şeması', '8 eğitim · 4 görülmemiş', '11 eğitim · 5 görülmemiş'],
        ['VOI ↔ oracle (Spearman)', '0,851', '0,833'],
        ['Doğruluk · konuşma başına ≤0,5 soru', '0,751', '0,752'],
      ],
      kiyasDipnot: 'Son iki satır görülmüş iş akışlarında, her model kendi dilindeki test setinde. İki test seti farklı olduğu için sayılar doğrudan kıyas değil, yön gösteriyor.',
      baglantilar: [
        { ad: 'MoganBERT-TR · Hugging Face', url: MOGANBERT_HF },
        { ad: 'MoganBERT-TR makalesi', url: MOGANBERT_MAKALE },
        { ad: 'MoganAI encoder ailesi', url: MOGAN_SITE },
      ],
    },
    laya: {
      p2: ['Mimarinin ve eğitimin ayrıntıları için ', 'Laya’nın kendi belgelerine',
           ' bakabilirsiniz. Laya’nın ağırlıklarını kullanmadık: encoder MoganBERT-TR, karar ve VOI başlıkları sıfırdan eğitildi. Eğitim, yayınladığımız lavoir paketiyle yapıldı. Bu sayfadaki bütün karşılaştırmalar Laya’nın çok dilli checkpoint’i Laya-multilingual (mmBERT tabanlı) ile yapıldı.'],
    },
    sorun: {
      p: ['Arayan kişi Alo 170’e “Merhaba, aramamda yardımcı olabilir misiniz?” dediğinde talep beş SGK biriminden herhangi birine ait olabilir. Tek geçişli bir karar modelinin bu durumda iki seçeneği var: ',
          'yine de en olası birimi seçmek ya da konuşmayı insana devretmek',
          '. Laya’nın önerdiği kullanım ikincisi: güven eşiğin altındaysa devret. Bir insan temsilci ise aramanın konusunu ve kimin adına arandığını sorup çağrıyı doğru birime kendisi yönlendirirdi.'],
      kart: {
        baslik: MODEL_AD_TR + ' VS LAYA-MULTILINGUAL',
        alt: 'aynı girdi · sgk_işlemleri/00115',
        dipnot: 'Aynı belirsiz ilk mesaj iki modele de veriliyor. Laya-multilingual’in güveni (1 − normalize entropi) 0,10’da kalıyor; önerilen kullanımla (güven < 0,85 → devret) konuşma insan kuyruğuna düşüyor, en iyi tahmini olan emeklilik de yanlış. ' + MODEL_AD_TR + ' önce konuyu, sonra kimin adına arandığını soruyor ve çağrıyı işveren_hizmetleri birimine doğru yönlendiriyor; kalan üç soruyu kararı değiştirmeyeceği için sormuyor. Soru sormasaydı emeklilik birimini seçecekti. Aynı iki soru–cevap Laya-multilingual’e hazır verilseydi o da ikinci adımda doğru birime karar verirdi: fark, hangi sorunun sorulacağını seçebilmekte. Laya-multilingual bu SGK iş akışını eğitimde görmedi; ' + MODEL_AD_TR + ' aynı şemayla eğitildi, bu konuşma ise test bölmesinden.',
        etiket: 'Animasyon: aynı belirsiz mesajda Laya-multilingual düşük güvenle konuşmayı insana devrediyor, ' + MODEL_AD_TR + ' iki soru sorup doğru birime (işveren_hizmetleri) yönlendiriyor.',
      },
    },
    voi: {
      kart: {
        baslik: 'VOI BAŞLIĞI NE ZAMAN DEVREYE GİRER?',
        alt: 'soru sorma döngüsü · sgk_işlemleri/00115',
        dipnot: 'Her ileri geçişte model, karar olasılıklarıyla birlikte henüz sorulmamış her slotun bilgi değerini (VOI) hesaplıyor; bunun için ek bir model çağrısı yok. En yüksek VOI eşiği (c = 0,05) geçerse o slotun sabit sorusu gönderiliyor, cevap konuşmaya eklenip model baştan çalışıyor. Hiçbir slot eşiği geçmediğinde ya da iki soru hakkı dolduğunda döngü bitiyor: model karar veriyor, hâlâ emin değilse konuşmayı insana devrediyor.',
        etiket: 'Animasyon: soru sorma döngüsü. Model iki kez döngüye girip konu ve başvuran slotlarını soruyor, üçüncü geçişte hiçbir slotun değeri eşiği geçmediği için döngüden çıkıp işveren_hizmetleri kararını veriyor.',
      },
    },
    veri: {
      p1: 'Türkçe iş akışları da şema olarak tanımlı: birimler, slotlar ve kurallar. İngilizce sürümdeki 12 şemanın kuralları ve önselleri birebir aktarıldı; metinler Türkçe yazıldı ve yerelleştirildi (TL eşikleri, yurt içi / yurt dışı, Türkçe ad listesi). Bunlara Türkiye’ye özgü dört akış eklendi: e-Devlet desteği, SGK işlemleri (Alo 170) ve belediye başvuruları (Alo 153) eğitimde; enerji dağıtımı (arıza, fatura, gaz kokusu) yalnızca testte. Mesajları ve cevapları Türkçe istemlerle bir dil modeli yazıyor, ayrı bir model ailesi gizli bilginin sızıp sızmadığını denetliyor.',
      hat: [
        { et: '01 · GİZLİ PROFİL', v: 'sorun: giriş yapamıyor\nvatandaşlık: yabancı uyruklu', not: 'kural → kurum yönlendirme' },
        { et: '02 · EKSİK MESAJ', v: '“e-Devlet’e bir türlü giremiyorum, ne yapmam gerekiyor?”', not: 'vatandaşlık mesajda yok' },
        { et: '03 · SORU–CEVAP', v: '“T.C. vatandaşı mısınız, yabancı uyruklu musunuz?”\n“Yabancı uyrukluyum.”', not: 'cevap profilden' },
      ],
      p2: ['Pilotlar Türkçeye özgü tuzaklar da çıkardı. ',
           '“Mağaza” pazaryerinde üçüncü taraf satıcı anlamına geliyor',
           ': “mağazanızdan aldım” diyen müşteri, denetleyici modele göre satıcının kim olduğunu ele veriyordu; değerler “doğrudan site / pazaryeri satıcısı” yapıldı. KVKK akışında ortam cümlesi gizli veri türünü sızdırıyordu, SGK ve belediye şemalarında anlamca örtüşen slotlar yeniden tasarlandı. İngilizce sürümün dersi Türkçede de geçerli: slotlar birbirinden anlamca bağımsız olmalı.'],
      p3: ['Karar başlığı yalnızca bu şemalarla eğitilmedi. ',
           'Yaklaşık 67 bin yerli Türkçe tek turlu örnek',
           ' de eğitime girdi: TrGLUE, all-nli-tr, duygu ve e-ticaret yorumları, KAP finansal duygu, saldırgan dil ve nefret söylemi, MASSIVE tr-TR, haber konusu, spam ve sahte haber. Buna Nemotron’un araç çağırma konuşmalarından Türkçeye çevirdiğimiz 145 bin konuşmadan kurulan 5,5 bin araç seçimi örneği ve MoganBERT-TR’nin ön eğitimindeki İngilizce payı kadar (20 bin) İngilizce örnek eklendi.'],
      kunye: () => [
        { k: 'ŞEMA', v: '11 eğitim · 5 görülmemiş' },
        { k: 'VOI ÖRNEKLERİ', v: '43,8k eğitim · 13,7k test' },
        { k: 'GENEL KARAR VERİSİ', v: '~67k Türkçe · 5,5k araç seçimi' },
        { k: 'TOPLAM', v: '~136k örnek · 16 GH200’de 49 dk' },
      ],
    },
    sonuc: {
      p1: MODEL_AD_TR + ' iki düzeyde değerlendirildi: kesin bilgi değerinin hesaplanabildiği Türkçe iş akışlarımız ve tek turlu Türkçe karar görevleri. İkisinde de Laya’nın çok dilli modeli (Laya-multilingual) aynı Türkçe talimat ve seçeneklerle karşılaştırıldı.',
      ozetTr: (d) => [
        { v: d.auc, k: 'diyalog AUC', not: `görülmüş Türkçe iş akışlarında; oracle ${d.oracle}` },
        { v: d.b05, k: '≤0,5 soruda doğruluk', not: `hiç sormayan modelden +${d.b2fark} puan` },
        { v: d.layaAuc, k: 'Laya-multilingual AUC', not: 'en iyi soruları biz verdiğimizde bile' },
        { v: d.sifir, k: 'sıfır atış görev', not: `TabiBench’te Laya-multilingual’in üstünde; ortalama +${d.sifirFark} puan` },
      ],
      thOlcut: 'ÖLÇÜT', thGoruldu: 'GÖRÜLMÜŞ · 11 ŞEMA', thGorulmedi: 'GÖRÜLMEMİŞ · 5 ŞEMA',
      sentBaslik: 'TÜRKÇE İŞ AKIŞLARIMIZ',
      sentAlt: 'sentetik test · kesin oracle ile',
      sentTr: [
        { k: 'acc', ad: 'İlk mesajda doğruluk / Bayes tavanı' },
        { k: 'auc', ad: 'Diyalog AUC · VOI / oracle' },
        { k: 'b05', ad: 'Doğruluk · konuşma başına ≤0,5 soru' },
        { k: 'rho', ad: 'VOI ↔ oracle (Spearman)' },
        { k: 'top1', ad: 'En değerli slotta uyum' },
        { k: 'ece', ad: 'ECE (düşük iyi)' },
      ],
      sentDipnotTr: 'Görülmüş: 11 eğitim şemasının ayrı test profilleri (7.140 örnek). Görülmemiş: eğitimde hiç olmayan 5 şema (6.539 örnek). Oracle gerçek bilgi değerini bilerek soruyor ama açgözlü (yalnızca bir soru ileriye bakıyor) ve kararı modelin kendi başlığı veriyor; bu yüzden VOI politikasının biraz altında kalabiliyor.',
      p2: ['VOI tarafı İngilizce sürüm kadar iyi: görülmüş iş akışlarında ',
           MODEL_AD_TR + ' soruları oracle’dan da iyi seçiyor',
           ' ve konuşma başına yarım sorudan az bir bütçede hiç sormayan modele göre 16,3, rastgele slot soran modele göre 7,9 puan daha doğru. Karar tarafı İngilizceden zayıf: soru sormadan verilen kararda Bayes tavanının 2,4 puan altında (aralık sıfırı içermiyor, yani model metni tam kullanmıyor), görülmemiş beş iş akışında ise tavanın çok altında.'],
      polBaslik: 'SORU SORMA POLİTİKALARI',
      polAlt: 'aynı Türkçe test seti',
      thPol: 'POLİTİKA', thAuc: 'AUC', thB05: '≤0,5 SORU',
      pol: {
        b2: 'Hiç sormaz',
        b3: 'Emin değilse rastgele slot sorar',
        b5: 'Olasılık kümesi > 1 ise sorar',
        voi: MODEL_AD_TR + ' (VOI)',
        oracle: 'Kesin VOI (açgözlü oracle)',
      },
      polDipnot: 'Kalın değer, oracle hariç sütunun en iyisi. Olasılık kümesi: olasılıkları toplamı 1 − α’ya ulaşan en küçük birim kümesi; birden fazla birim içeriyorsa VOI’nin seçtiği slot soruluyor, α taranıyor. — ölçülmedi.',
      layaBaslik: 'LAYA-MULTILINGUAL AYNI İŞ AKIŞLARINDA',
      layaAlt: 'Türkçe · aşamalı sorular',
      thLayaTr: 'LAYA-MULTI', thBizTr: MODEL_AD_TR,
      layaSatir: {
        ilk: 'İlk mesajda doğruluk (soru yok)',
        b3: 'AUC · rastgele soru',
        oracle: 'AUC · oracle soru',
        voi: 'AUC · modelin kendi seçtiği soru',
        iki: 'İki oracle sorudan sonra doğruluk',
      },
      soramaz: 'soramaz',
      layaDipnot: (d) => `Laya-multilingual soru seçemediği için sorular dışarıdan seçildi (rastgele ya da oracle), cevaplar aynı şekilde konuşmaya eklendi ve kararı Laya-multilingual verdi. Laya’nın kendi kuralıyla (güven < 0,85 → devret) görülmüş iş akışlarında insana devredilen ilk mesaj oranı %${d.oran}; kalan mesajlarda doğruluk ${d.acc}. Laya-multilingual bu şemaları eğitimde görmedi: gösterilen, soruyu kimin seçtiği ve cevabın ne kadar kullanılabildiği.`,
      p3: ['Laya-multilingual Türkçe iş akışlarında zayıf ve kalibrasyonu kötü (ECE 0,44–0,46). ',
           'En iyi soruları dışarıdan versek bile iki sorudan sonra doğruluğu 0,42–0,43’te kalıyor',
           '; ' + MODEL_AD_TR + ' aynı durumda 0,875’e çıkıyor. ' + MODEL_AD_TR + '’nin kendi seçtiği sorularla elde ettiği AUC, Laya-multilingual’e oracle soru verildiğindekinin iki katı.'],
      sifirBaslik: 'SIFIR ATIŞ: TABIBENCH',
      sifirAlt: 'iki modelin de eğitiminde yok · 8 görev',
      thGorev: 'GÖREV', thAcc: 'DOĞRULUK', thF1: 'MACRO-F1',
      gorev: {
        haber: 'Haber kategorisi (5)', tweet: 'Tweet duygusu (4)', nefret: 'Cinsiyete dayalı nefret (3)',
        sick: 'SICK ilişkililik (1–5)', tibbi: 'Tıbbi NLI (3)', atif: 'Atıf amacı (3)',
        rol: 'Cümle rolü (5)', tez: 'Tez alanı (10 seçenek)', ort: 'Ortalama',
      },
      sifirDipnot: 'TabiBench’in (Boğaziçi TabiLab) karar görevleri; yalnızca test bölmeleri, görev başına en fazla 1.000 vaka, seed 13. Eğitimde görülen kaynaklar (ürün yorumları, SNLI-TR, MultiNLI-TR, STSb-TR) dışarıda bırakıldı. TabiBench’in kendi sayıları ince ayarlı modellerle; buradaki kıyas yalnızca iki karar modeli arasında.',
      p4: ['Sıfır atışta ', MODEL_AD_TR + ' sekiz görevin yedisinde önde',
           ': ortalamada doğrulukta 10,1, macro-F1’de 8,7 puan; ECE de sekizin yedisinde daha iyi. Tek kayıp, alaycı sınıfı olan küçük tweet duygusu seti (146 vaka): model orada aşırı emin.'],
      alanBaslik: 'TÜRKÇE KARAR GÖREVLERİ',
      alanAlt: 'eğitim bölmeleri ' + MODEL_AD_TR + '’de var · adil kıyas değil',
      alan: {
        cola: 'TrGLUE CoLA', sst2: 'TrGLUE SST-2', mrpc: 'TrGLUE MRPC', qqp: 'TrGLUE QQP', mnli: 'TrGLUE MNLI',
        qnli: 'TrGLUE QNLI', rte: 'TrGLUE RTE', stsb: 'TrGLUE STS-B', massive: 'MASSIVE-tr niyet (20 seçenek)',
        saldirgan: 'Saldırgan dil', duygu: 'Duygu', yildiz: 'E-ticaret yıldız', urun: 'Ürün yorumu',
        haberKonu: 'Haber konusu', spam: 'Spam', sahte: 'Sahte haber', nefretH: 'Nefret söylemi',
      },
      alanDipnot: 'Test bölmeleri, görev başına en fazla 1.000 vaka. Bu 17 görevin eğitim bölmeleri ' + MODEL_AD_TR + '’nin Türkçe genel verisinde var, Laya-multilingual bunları görmedi; bu yüzden aradaki fark, alan içi eğitimle sıfır atış arasındaki farkı da içeriyor. 17 görevin 15’inde ' + MODEL_AD_TR + ' önde (ortalama doğruluk 0,749’a karşı 0,547).',
    },
    sinir: {
      liste: [
        'Görülmüş iş akışlarında karar, Bayes tavanının 2,4 puan altında ve fark istatistiksel olarak anlamlı; İngilizce sürümde fark anlamlı değildi. Model Türkçe metni henüz tam kullanmıyor.',
        'Görülmemiş beş iş akışında karar zayıf (0,45’e karşı tavan 0,68); en zorlanılan akış enerji dağıtımı.',
        'Türkçe karar görevlerinin 17’sinde eğitim bölmeleri eğitim verisinde var; Laya-multilingual ile adil kıyas için sıfır atış sonuçlarına (TabiBench) bakılmalı.',
        'Sıfır atışta seçenek sırasına duyarlılık daha yüksek; küçük tweet duygusu setinde model aşırı emin.',
        'Soru metinleri şablondan geliyor. MoganBERT-TR ile soruyu modelin kendisine yazdırmayı denedik; MLM sonrası üretim yeteneği yeterli değil.',
        'Türkçe iş akışları sentetik; SGD ve ABCD’nin Türkçe karşılığı olmadığı için gerçek Türkçe müşteri konuşmalarıyla değerlendirme henüz yok.',
      ],
    },
    kaynak: {
      liste: [
        { ad: 'MoganBERT-TR (Hugging Face)', not: 'encoder', url: MOGANBERT_HF },
        { ad: 'MoganBERT-TR: Türkçe encoder, CLM → MLM müfredatı', not: 'encoder makalesi · arXiv', url: MOGANBERT_MAKALE },
        { ad: 'MoganAI encoder ailesi', not: 'MoganBERT sitesi', url: MOGAN_SITE },
        { ad: 'Laya: typed decisions in a single forward pass', not: 'karar mimarisi ve eğitim hedefi', url: LAYA_GITHUB },
        { ad: 'Laya checkpoint’leri (Hugging Face)', not: 'Laya-multilingual karşılaştırması', url: LAYA_HF },
        { ad: 'Rao ve Daumé III (2018). Learning to Ask Good Questions', not: 'EVPI ile açıklayıcı soru sıralama', url: 'https://aclanthology.org/P18-1255/' },
      ],
    },
  },

  en: {
    modelAd: MODEL_AD_TR,
    navSira: ['giris', 'moganbert', 'laya', 'voi', 'veri', 'sonuc', 'kaynak'],
    hero: {
      alt: 'A Turkish decision model · built on MoganBERT-TR',
      logo: { src: 'lavoir-tr-logo.png', w: 1248, h: 340, gen: 'max-w-[290px] sm:max-w-[340px] md:max-w-[390px]' },
      baglanti: { hf: LAVOIR_TR_HF, paper: '', kod: LAVOIR_KOD },
      ozet: [MODEL_AD_TR + ' is the Turkish version of ' + MODEL_AD + ', ',
             'built on MoganBERT-TR, the Turkish encoder we trained from scratch',
             '. The same decision architecture and VOI head were trained on Turkish workflows: in Turkish customer messages about e-Government, social security, municipal services, data protection or banking, it asks for the missing information and decides again once it has the answer.'],
      metaSol: 'VERSION 1 · TURKISH',
      gercek: [
        { k: 'ENCODER', v: 'MoganBERT-TR (MoganAI)' },
        { k: 'MODEL SIZE', v: '164M parameters' },
        { k: 'WORKFLOWS', v: '16 Turkish schemas' },
        { k: 'FOUNDATION', v: 'Laya decision architecture' },
      ],
    },
    moganbert: {
      baslik: 'BUILT ON MOGANBERT-TR',
      p1: ['The encoder of ' + MODEL_AD_TR + ' is ', 'MoganBERT-TR',
           ': a ModernBERT-architecture encoder we trained from scratch for Turkish with a CLM → MLM curriculum. The decision and VOI heads were trained from scratch on top of it; no weights were transferred from a multilingual model or from the English ' + MODEL_AD + '.'],
      p2: ['Using an encoder built for Turkish has two effects. ',
           'The same Turkish message takes 122 tokens with MoganBERT-TR’s tokenizer and 222 with ModernBERT’s',
           ': the sequence is shorter, leaving more room for the workflow’s options and slots. The model is also less than half the size of the English version, yet just as good at choosing questions.'],
      p3: ['MoganBERT-TR’s [CLS] token was not used in pretraining. That does not matter for ' + MODEL_AD_TR + ': the decision and the value of information are read from the [MASK] markers in front of each option and slot, not from [CLS]. The special-token layout matches Laya’s sequence format, and the context length is 1,024 tokens.'],
      kiyasBaslik: MODEL_AD + ' AND ' + MODEL_AD_TR,
      kiyasAlt: 'same architecture · different encoder',
      thOzellik: 'PROPERTY',
      kiyas: [
        ['Encoder', 'ModernBERT-large', 'MoganBERT-TR (MoganAI)'],
        ['Total parameters', '421M', '164M'],
        ['Same Turkish message', '222 tokens', '122 tokens'],
        ['Training data', '~104k examples', '~136k examples (20k English)'],
        ['Workflow schemas', '8 training · 4 unseen', '11 training · 5 unseen'],
        ['VOI ↔ oracle (Spearman)', '0.851', '0.833'],
        ['Accuracy · ≤0.5 questions per conversation', '0.751', '0.752'],
      ],
      kiyasDipnot: 'The last two rows are on seen workflows, each model on the test set in its own language. The test sets differ, so the numbers show the direction rather than a direct comparison.',
      baglantilar: [
        { ad: 'MoganBERT-TR · Hugging Face', url: MOGANBERT_HF },
        { ad: 'MoganBERT-TR paper', url: MOGANBERT_MAKALE },
        { ad: 'MoganAI encoder family', url: MOGAN_SITE },
      ],
    },
    laya: {
      p2: ['For the details of the architecture and training see ', 'Laya’s own documentation',
           '. We did not use Laya’s weights: the encoder is MoganBERT-TR and the decision and VOI heads were trained from scratch, with our released lavoir package. All comparisons on this page use Laya’s multilingual checkpoint, Laya-multilingual (based on mmBERT).'],
    },
    sorun: {
      p: ['When a caller to the social security hotline (Alo 170) says “Merhaba, aramamda yardımcı olabilir misiniz?” (“Hello, can you help me with my call?”), the request could belong to any of five units. A single-pass decision model has two options here: ',
          'pick the most likely unit anyway, or hand the conversation to a human',
          '. Laya recommends the second: hand off when confidence is below a threshold. A human agent would ask what the call is about and on whose behalf, and route it themselves.'],
      kart: {
        baslik: MODEL_AD_TR + ' VS LAYA-MULTILINGUAL',
        alt: 'same input · sgk_işlemleri/00115',
        dipnot: 'The same ambiguous first message goes to both models. Laya-multilingual’s confidence (one minus the normalized entropy) stays at 0.10; with the recommended usage (confidence < 0.85 → hand off) the conversation lands in the human queue, and its best guess, emeklilik (retirement), is wrong anyway. ' + MODEL_AD_TR + ' asks about the topic, then on whose behalf the call is, and routes correctly to işveren_hizmetleri (employer services); it skips the other three questions because they would not change the decision. Without asking it would have picked emeklilik. Given the same two questions and answers up front, Laya-multilingual would also reach the right unit at the second step: the difference is choosing which question to ask. Laya-multilingual never saw this social-security workflow in training; ' + MODEL_AD_TR + ' was trained on the same schema, and this conversation is from the test split.',
        etiket: 'Animation: on the same ambiguous message Laya-multilingual hands off with low confidence, while ' + MODEL_AD_TR + ' asks two questions and routes to the right unit (işveren_hizmetleri).',
      },
    },
    voi: {
      kart: {
        baslik: 'WHEN DOES THE VOI HEAD ACT?',
        alt: 'the asking loop · sgk_işlemleri/00115',
        dipnot: 'On every forward pass the model computes, together with the decision probabilities, the value of information (VOI) of every slot not asked yet; there is no extra model call. If the highest VOI clears the threshold (c = 0.05), that slot’s fixed question is sent, the answer is appended to the conversation and the model runs again. The loop ends when no slot clears the threshold or the two-question budget is used: the model decides, or hands the conversation to a human if it is still unsure.',
        etiket: 'Animation: the asking loop. The model loops twice, asking the konu (topic) and başvuran (on whose behalf) slots; on the third pass no slot clears the threshold, so it exits the loop and decides işveren_hizmetleri.',
      },
    },
    veri: {
      p1: 'The Turkish workflows are schemas too: teams, slots and rules. The rules and priors of the 12 English schemas were carried over exactly; the texts were written in Turkish and localised (lira thresholds, domestic / abroad, a Turkish name list). Four Turkey-specific workflows were added: e-Government support, social security (Alo 170) and municipal requests (Alo 153) in training, and energy distribution (outage, billing, gas smell) in the test set only. A language model writes the messages and answers from Turkish prompts, and a model from a different family checks whether hidden information leaks.',
      hat: [
        { et: '01 · HIDDEN PROFILE', v: 'sorun: giriş yapamıyor\nvatandaşlık: yabancı uyruklu', not: 'rule → referral to another office' },
        { et: '02 · INCOMPLETE MESSAGE', v: '“e-Devlet’e bir türlü giremiyorum, ne yapmam gerekiyor?”', not: 'citizenship not in the message' },
        { et: '03 · QUESTION AND ANSWER', v: '“T.C. vatandaşı mısınız, yabancı uyruklu musunuz?”\n“Yabancı uyrukluyum.”', not: 'answer from the profile' },
      ],
      p2: ['The pilots also turned up traps specific to Turkish. ',
           '“Mağaza” (store) means a third-party seller on a marketplace',
           ': a customer saying “I bought it from your store” gave away the seller according to the checking model, so the values became “directly from the site / marketplace seller”. In the data-protection workflow a scene-setting sentence leaked the hidden data type, and overlapping slots were redesigned in the social-security and municipal schemas. The lesson from the English version holds in Turkish: slots must be independent in meaning.'],
      p3: ['The decision head was not trained on these schemas alone. ',
           'About 67k native Turkish single-turn examples',
           ' went into training as well: TrGLUE, all-nli-tr, sentiment and e-commerce reviews, KAP financial sentiment, offensive language and hate speech, MASSIVE tr-TR, news topics, spam and fake news. On top of that come 5.5k tool-choice examples built from 145k Nemotron tool-calling conversations we translated into Turkish, and 20k English examples, matching the English share of MoganBERT-TR’s pretraining.'],
      kunye: () => [
        { k: 'SCHEMAS', v: '11 training · 5 unseen' },
        { k: 'VOI EXAMPLES', v: '43.8k train · 13.7k test' },
        { k: 'GENERAL DECISION DATA', v: '~67k Turkish · 5.5k tool choice' },
        { k: 'TOTAL', v: '~136k examples · 49 min on 16 GH200' },
      ],
    },
    sonuc: {
      p1: MODEL_AD_TR + ' was evaluated at two levels: our Turkish workflows, where the exact value of information can be computed, and single-turn Turkish decision tasks. In both, Laya’s multilingual model (Laya-multilingual) was compared with the same Turkish instructions and options.',
      ozetTr: (d) => [
        { v: d.auc, k: 'dialogue AUC', not: `on seen Turkish workflows; oracle ${d.oracle}` },
        { v: d.b05, k: 'accuracy at ≤0.5 questions', not: `+${d.b2fark} points over never asking` },
        { v: d.layaAuc, k: 'Laya-multilingual AUC', not: 'even when we give it the best questions' },
        { v: d.sifir, k: 'zero-shot tasks', not: `above Laya-multilingual on TabiBench; +${d.sifirFark} points on average` },
      ],
      thOlcut: 'METRIC', thGoruldu: 'SEEN · 11 SCHEMAS', thGorulmedi: 'UNSEEN · 5 SCHEMAS',
      sentBaslik: 'OUR TURKISH WORKFLOWS',
      sentAlt: 'synthetic test · with an exact oracle',
      sentTr: [
        { k: 'acc', ad: 'First-message accuracy / Bayes ceiling' },
        { k: 'auc', ad: 'Dialogue AUC · VOI / oracle' },
        { k: 'b05', ad: 'Accuracy · ≤0.5 questions per conversation' },
        { k: 'rho', ad: 'VOI ↔ oracle (Spearman)' },
        { k: 'top1', ad: 'Agreement on the most valuable slot' },
        { k: 'ece', ad: 'ECE (lower is better)' },
      ],
      sentDipnotTr: 'Seen: held-out profiles of the 11 training schemas (7,140 examples). Unseen: 5 schemas never seen in training (6,539 examples). The oracle asks knowing the true value of information, but it is greedy (it looks one question ahead) and decides with the model’s own head, so it can end up slightly below the VOI policy.',
      p2: ['The VOI side is as good as in the English version: on seen workflows ',
           MODEL_AD_TR + ' picks questions even better than the oracle',
           ', and under a budget of less than half a question per conversation it is 16.3 points more accurate than never asking and 7.9 points more accurate than asking a random slot. The decision side is weaker than in English: without asking it is 2.4 points below the Bayes ceiling (the interval excludes zero, so the model does not use the text fully), and on the five unseen workflows it stays far below the ceiling.'],
      polBaslik: 'ASKING POLICIES',
      polAlt: 'same Turkish test set',
      thPol: 'POLICY', thAuc: 'AUC', thB05: '≤0.5 QUESTIONS',
      pol: {
        b2: 'Never asks',
        b3: 'Asks a random slot when unsure',
        b5: 'Asks when the probability set > 1',
        voi: MODEL_AD_TR + ' (VOI)',
        oracle: 'Exact VOI (greedy oracle)',
      },
      polDipnot: 'Bold marks the best value in the column, excluding the oracle. Probability set: the smallest set of teams whose probabilities add up to 1 − α; if it holds more than one team, the slot chosen by VOI is asked, with α swept. — not measured.',
      layaBaslik: 'LAYA-MULTILINGUAL ON THE SAME WORKFLOWS',
      layaAlt: 'Turkish · questions in stages',
      thLayaTr: 'LAYA-MULTI', thBizTr: MODEL_AD_TR,
      layaSatir: {
        ilk: 'First-message accuracy (no questions)',
        b3: 'AUC · random question',
        oracle: 'AUC · oracle question',
        voi: 'AUC · question chosen by the model',
        iki: 'Accuracy after two oracle questions',
      },
      soramaz: 'cannot ask',
      layaDipnot: (d) => `Laya-multilingual cannot choose questions, so the questions were chosen outside it (random or oracle), the answers were appended to the conversation in the same way, and Laya-multilingual made the decision. With Laya’s own rule (confidence < 0.85 → hand off) ${d.oran}% of first messages on seen workflows go to a human; on the rest its accuracy is ${d.acc}. Laya-multilingual never saw these schemas: what this shows is who picks the question and how well the answer is used.`,
      p3: ['Laya-multilingual is weak and poorly calibrated on the Turkish workflows (ECE 0.44–0.46). ',
           'Even when we give it the best questions, its accuracy after two questions stays at 0.42–0.43',
           '; ' + MODEL_AD_TR + ' reaches 0.875 in the same setting. The AUC ' + MODEL_AD_TR + ' reaches with the questions it picks itself is twice what Laya-multilingual reaches when handed oracle questions.'],
      sifirBaslik: 'ZERO-SHOT: TABIBENCH',
      sifirAlt: 'seen by neither model in training · 8 tasks',
      thGorev: 'TASK', thAcc: 'ACCURACY', thF1: 'MACRO-F1',
      gorev: {
        haber: 'News category (5)', tweet: 'Tweet sentiment (4)', nefret: 'Gender-based hate (3)',
        sick: 'SICK relatedness (1–5)', tibbi: 'Medical NLI (3)', atif: 'Citation intent (3)',
        rol: 'Sentence role (5)', tez: 'Thesis field (10 options)', ort: 'Average',
      },
      sifirDipnot: 'Decision tasks from TabiBench (Boğaziçi TabiLab); test splits only, at most 1,000 cases per task, seed 13. Sources seen in training (product reviews, SNLI-TR, MultiNLI-TR, STSb-TR) were left out. TabiBench’s own numbers come from fine-tuned models; the comparison here is only between the two decision models.',
      p4: ['Zero-shot, ', MODEL_AD_TR + ' leads on seven of the eight tasks',
           ': 10.1 points in accuracy and 8.7 in macro-F1 on average, with better ECE on seven of eight. The one loss is the small tweet sentiment set (146 cases) with a sarcasm class, where the model is overconfident.'],
      alanBaslik: 'TURKISH DECISION TASKS',
      alanAlt: 'training splits are in ' + MODEL_AD_TR + '’s data · not a fair comparison',
      alan: {
        cola: 'TrGLUE CoLA', sst2: 'TrGLUE SST-2', mrpc: 'TrGLUE MRPC', qqp: 'TrGLUE QQP', mnli: 'TrGLUE MNLI',
        qnli: 'TrGLUE QNLI', rte: 'TrGLUE RTE', stsb: 'TrGLUE STS-B', massive: 'MASSIVE-tr intent (20 options)',
        saldirgan: 'Offensive language', duygu: 'Sentiment', yildiz: 'E-commerce stars', urun: 'Product review',
        haberKonu: 'News topic', spam: 'Spam', sahte: 'Fake news', nefretH: 'Hate speech',
      },
      alanDipnot: 'Test splits, at most 1,000 cases per task. The training splits of these 17 tasks are in ' + MODEL_AD_TR + '’s Turkish general data and Laya-multilingual never saw them, so the gap also contains the difference between in-domain training and zero-shot. ' + MODEL_AD_TR + ' leads on 15 of the 17 (mean accuracy 0.749 vs 0.547).',
    },
    sinir: {
      liste: [
        'On seen workflows the decision is 2.4 points below the Bayes ceiling and the gap is statistically significant; in the English version it was not. The model does not yet use the Turkish text fully.',
        'On the five unseen workflows the decision is weak (0.45 against a ceiling of 0.68); energy distribution is the hardest.',
        'The training splits of the 17 Turkish decision tasks are in the training data; for a fair comparison with Laya-multilingual see the zero-shot results (TabiBench).',
        'Zero-shot, sensitivity to option order is higher, and the model is overconfident on the small tweet sentiment set.',
        'Question wording comes from templates. We tried letting MoganBERT-TR write the questions itself; after MLM training its generation ability is not good enough.',
        'The Turkish workflows are synthetic; SGD and ABCD have no Turkish counterpart, so there is no evaluation on real Turkish customer conversations yet.',
      ],
    },
    kaynak: {
      liste: [
        { ad: 'MoganBERT-TR (Hugging Face)', not: 'encoder', url: MOGANBERT_HF },
        { ad: 'MoganBERT-TR: a Turkish encoder with a CLM → MLM curriculum', not: 'encoder paper · arXiv', url: MOGANBERT_MAKALE },
        { ad: 'MoganAI encoder family', not: 'MoganBERT site', url: MOGAN_SITE },
        { ad: 'Laya: typed decisions in a single forward pass', not: 'decision architecture and training objective', url: LAYA_GITHUB },
        { ad: 'Laya checkpoints (Hugging Face)', not: 'Laya-multilingual comparison', url: LAYA_HF },
        { ad: 'Rao and Daumé III (2018). Learning to Ask Good Questions', not: 'ranking clarifying questions with EVPI', url: 'https://aclanthology.org/P18-1255/' },
      ],
    },
  },
};
